---
- hosts: all
  become: yes
  gather_facts: false

  tasks:
    - name: Ensure Httpd is installed                  
      yum:
        name: httpd
        state: latest
    - name: start httpd service
      service:
        name: httpd
        state: started
        enabled: yes
    - name: create index.html
      file:
        path: /var/www/html/index.html
        state: touch   
    - name: Add a line in index.html
      lineinfile:
        path: /var/www/html/index.html
        line: "Hello World"        
